#
# MIT License
#
# Copyright (c) 2020-present Cloudogu GmbH and Contributors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# Default values for SCM-Manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  # image.repository --  Name of SCM-Manager image
  repository: ${docker.repository}
  # image.tag -- Tag of SCM-Manager image
  tag: ${docker.tag}
  # image.pullPolicy -- SCM-Manager image pull policy
  pullPolicy: IfNotPresent

# nameOverride -- Override the resource name prefix
nameOverride: ""
# fullnameOverride -- Override the full resource names
fullnameOverride: ""

service:
  # service.type -- k8s service type
  type: LoadBalancer
  # service.port -- k8s service port
  port: 80

ingress:
  # ingress.enabled -- Enables ingress
  enabled: false
  # ingress.annotations -- Ingress annotations
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # ingress.path -- Ingress path
  path: /
  # ingress.hosts -- Ingress hosts
  hosts:
    - scm-manager.local
  # ingress.tls -- Ingress TLS configuration
  tls: []
  #  - secretName: scm-manager-tls
  #    hosts:
  #      - scm-manager.local

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  # persistence.enabled -- Enable the use of a PVC for SCM-Manager home
  enabled: true
  ## ghost data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  # persistence.accessMode -- The PVC access mode
  accessMode: ReadWriteOnce
  # persistence.size -- The size of the PVC
  size: 40Gi

# resources -- Resources allocation (Requests and Limits)
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #limits:
  #  cpu: 2000m
  #  memory: 2048Mi
  #requests:
  #  cpu: 50m
  #  memory: 256Mi

# nodeSelector -- Node labels for pod assignment
nodeSelector: {}

# tolerations -- Toleration labels for pod assignment
tolerations: []

# affinity -- Affinity settings
affinity: {}
